### ISSUE TITLE
daisy.run_blockwise incompatible with Python 3.5 and older

### ISSUE THREAD

**Issue by hanslovsky** [funkelab/daisy#1]
The local scheduler uses asyncio functionality that is not available in Python 3.5:
```
Traceback (most recent call last):
  File "/usr/local/bin/predict-affinities", line 11, in <module>
    load_entry_point('eqip==0.3.1.dev0', 'console_scripts', 'predict-affinities')()
  File "/usr/local/lib/python3.5/dist-packages/eqip/inference/backend_daisy.py", line 328, in predict_affinities_daisy
    read_write_conflict=False)
  File "/usr/local/lib/python3.5/dist-packages/daisy/scheduler.py", line 574, in run_blockwise
    return distribute([{'task': BlockwiseTask()}])
  File "/usr/local/lib/python3.5/dist-packages/daisy/scheduler.py", line 602, in distribute
    return Scheduler().distribute(dependency_graph)
  File "/usr/local/lib/python3.5/dist-packages/daisy/scheduler.py", line 69, in distribute
    self._start_tcp_server()
  File "/usr/local/lib/python3.5/dist-packages/daisy/scheduler.py", line 162, in _start_tcp_server
    asyncio._set_running_loop(new_event_loop)
AttributeError: module 'asyncio' has no attribute '_set_running_loop'
```

It probably does not make sense to make `daisy.run_blockwise` compatible with Python 3.5 because
> [the asyncio module has received new features, significant usability and performance improvements, and a fair amount of bug fixes. Starting with Python 3.6 the asyncio module is no longer provisional and its API is considered stable.](https://docs.python.org/3/whatsnew/3.6.html)

Unfortunately, tensorflow docker images only come with Ubuntu 16.04 and Python3.5. The solution for users is to use conda (or pip) and install tensorflow-gpu into a virtual environment. Unfortunately, I do not see a good solution for daisy to ensure that users have an appropriate version of Python on their system:
  - adding [`python_requires='>=3.6'`](https://stackoverflow.com/a/19535016/1725687) to `setup.py` would prohibit the use of the tensorflow docker containers (come only with Python3.5), which  is probably required for lsf scenarios

I suggest to use this issue as a note to users who would like to run`daisy.run_blockwise` in a non-lsf setting, maybe also linking to it in `README.md`.

**Comment by trivoldus28** [comment]
It's a bit strange that you got the error
`AttributeError: module 'asyncio' has no attribute '_set_running_loop'` 
as it seems that the [source](https://github.com/python/cpython/blob/3.5/Lib/asyncio/events.py#L9) for 3.5 does have `_set_running_loop` function? (And I seem to remember that I was also testing with 3.5 before)

Maybe this is included only in newer Python 3.5? Can you check your /usr/lib Python file to see if your distribution indeed does not have that function?

**Comment by hanslovsky** [comment]
Wow, that is super strange:
```sh
root@b8745cc22889:/src/eqip# ls -d /usr/lib/python*
/usr/lib/python2.7  /usr/lib/python3  /usr/lib/python3.5
root@b8745cc22889:/src/eqip# grep -rnH '_set_running_loop' /usr/lib/python*
root@b8745cc22889:/src/eqip#
```

Maybe it is the Ubuntu 16.04 Python 3.5.

Anyway, I can resolve this issue by using conda, so, from my side, this does not need more investigating.

**Comment by hanslovsky** [comment]
> Maybe it is the Ubuntu 16.04 Python 3.5.

Or is it possible that any `pip` installs would mess with the system python `asyncio`?

**Comment by trivoldus28** [comment]
Looks like the method is only available on 3.5.3+, which is released in Jan 2017 so would make sense if it wasn't in Ubuntu 16.04.

**Comment by trivoldus28** [comment]
As a quick background for this issue, the method `_set_running_loop` was used to overcome a bug that exists with `asyncio` and `multiprocessing` where the `asyncio` thread is not properly handled when the process running daisy scheduler is forked to create a worker process. It was then necessary to use `_set_running_loop` to create and set a new `IOLoop`.

Unfortunately I don't see an easy way to not use `_set_running_loop`, which likely means setting `python_requires='>=3.6'`

**Comment by hanslovsky** [comment]
Thanks for looking into this and shedding some light on it @trivoldus28 

Luckily, at least for me, the conda workaround is a good (maybe even better) solution.

**Comment by clbarnes** [comment]
3.5 is EOL, this can probably be closed.

**Comment by funkey** [comment]
Agreed.
