### ISSUE TITLE
Including a license file

### ISSUE THREAD

**Issue by jakirkham** [funkelab/daisy#14]
It would be good to include a license file in the project. This is needed for other people that would like to use the project. It also is often required when creating packages for users to install.

Additionally it would be good to add [a `MANIFEST.in`, which includes the license file]( https://github.com/pypa/sampleproject/blob/cbabca3f3f54a6e053e231d4cc89a46550049107/MANIFEST.in#L4-L5 ) and add [a `setup.cfg` that also includes a license file]( https://github.com/pypa/sampleproject/blob/cbabca3f3f54a6e053e231d4cc89a46550049107/setup.cfg#L1-L4 ). This ensures that other package types produce include and ship the license file for easier downstream consumption.

**Comment by jakirkham** [comment]
cc @hanslovsky (for awareness)

**Comment by cmalinmayor** [comment]
Looks like there is now an MIT license file and it is included in the pyproject.toml.
