### ISSUE TITLE
Can only import tensorflow (implicit or explicit) inside process_function of daisy.run_blockwise

### ISSUE THREAD

**Issue by hanslovsky** [funkelab/daisy#2]
When trying to use `tensorflow` in the workers of `daisy.run_blockwise`, `tensorflow` may only be imported inside the `process_function`. This includes implicit imports, e.g. through [`gunpowder`](https://github.com/funkey/gunpowder/blob/06dfc8f5527775e2dc741fd0f33898e3d02bc2c2/gunpowder/__init__.py#L19). For some reason, `tensorflow` does not [play well with `multiprocessing`](https://github.com/tensorflow/tensorflow/issues/8220). The solution is to make sure that `tensorflow` is [imported exclusively in the relevant subprocesses (and not in the main process)](https://github.com/tensorflow/tensorflow/issues/8220#issuecomment-383462576). This is not an issue that arises from within daisy but it would be helpful for users to know how to resolve this issue (maybe even add a link to this issue to `README.md`).

A simple example of what does not work:
```python
import daisy
import gunpowder

def process_function():
    scheduler = ClientScheduler()
    while True:
        # do something with gunpowder, e.g. build pipeline and run prediction on requested blocks

daisy.run_blockwise(
    ...
    process_function=process_function,
    num_workers=2) # no issues if only one worker
```
and what works:
```python
import daisy

def process_function():
    import gunpowder
    scheduler = ClientScheduler()
    while True:
        # do something with gunpowder, e.g. build pipeline and run prediction on requested blocks

daisy.run_blockwise(
    ...
    process_function=process_function,
    num_workers=2)
```

**Comment by pattonw** [comment]
I'm closing this since it comes from before the v1.0 refactor and release
