### ISSUE TITLE
Why force the size of chunks to be smaller than 256

### ISSUE THREAD

**Issue by weihuang527** [funkelab/daisy#30]
In line 182 of datasets.py, 'chunk_size' is obtained by 'get_chunk_size ' which controls the 'chunk_size' to be smaller than 256. 256 is not an adjustable parameter. I suggest changing it to an adjustable parameter so that the user can obtain the size of chunks they like.

**Comment by pattonw** [comment]
This has been moved to `funlib.persistence`
