### ISSUE TITLE
pip installs older version of daisy

### ISSUE THREAD

**Issue by msayr** [funkelab/daisy#45]
Running Ubuntu 20.04, python 3.6, pip 21.3.1 in conda venv

![image](https://github.com/funkelab/daisy/assets/52462209/ac07978a-83b5-45f9-ad60-e80391dfa656)

Trying w/out cache directory:
![image](https://github.com/funkelab/daisy/assets/52462209/911b2449-58f3-44a5-8754-091ce4aae1a6)

Trying using specific version:
![image](https://github.com/funkelab/daisy/assets/52462209/8ec82003-508f-4f5f-b27f-71f9465ac84f)

**Comment by msayr** [comment]
Just realized that this because daisy v1.0 requires python>=3.7, the issue is on my end. Thanks anyhow!

**Comment by trivoldus28** [comment]
Yup that's right! Glad you got it 😀
